FROM localhost:5000/base

RUN wget https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz \
 && tar -C /opt -xvzf apache-maven-3.5.3-bin.tar.gz \
 && ln -s /opt/apache-maven-3.5.3 /opt/maven \
 && rm -f apache-maven-3.5.3-bin.tar.gz \
 && update-alternatives --install "/usr/bin/mvn" "mvn" "/opt/maven/bin/mvn" 1 \
 && update-alternatives --set "mvn" "/opt/maven/bin/mvn"
